import jenkins.model.*
import com.cloudbees.plugins.credentials.common.StandardUsernameCredentials
import com.cloudbees.plugins.credentials.CredentialsProvider
import groovy.json.JsonSlurper
import org.yaml.snakeyaml.Yaml

String basePath = 'Test'
pJobPath = 'Test/Testy'

folder(pJobPath) {
        description("<h1>${pDescription}</h1>\n<p><span style=\"color: #ff0000;\">** Generated by Jenkins **</span></p>")
        displayName(pDisplayName)
 }
